@echo off
echo Setting remote...
git remote remove origin
git remote add origin https://github.com/VishalBhagat01/Railway-Moniter.git
echo Renaming branch...
git branch -M main
echo Adding files...
git add .
echo Committing...
git commit -m "Upload project files"
echo Pushing...
git push -u origin main
echo Done.
